package system.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_area.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_area.BA_CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_area.BA_NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_area.BA_LEVEL
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_area.ID
     *
     * @return the value of blog_area.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_area.ID
     *
     * @param id the value for blog_area.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_area.BA_CODE
     *
     * @return the value of blog_area.BA_CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_area.BA_CODE
     *
     * @param code the value for blog_area.BA_CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_area.BA_NAME
     *
     * @return the value of blog_area.BA_NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_area.BA_NAME
     *
     * @param name the value for blog_area.BA_NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_area.BA_LEVEL
     *
     * @return the value of blog_area.BA_LEVEL
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_area.BA_LEVEL
     *
     * @param level the value for blog_area.BA_LEVEL
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level;
    }
}