package system.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_SUMMARY
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_LABEL_ID
     *
     * @mbggenerated
     */
    private String labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_ARITICLE_TYPE
     *
     * @mbggenerated
     */
    private String ariticleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_OPERATION_TIME
     *
     * @mbggenerated
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_article.BA_READ_AMOUNT
     *
     * @mbggenerated
     */
    private Integer readAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.ID
     *
     * @return the value of blog_article.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.ID
     *
     * @param id the value for blog_article.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_USER_ID
     *
     * @return the value of blog_article.BA_USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_USER_ID
     *
     * @param userId the value for blog_article.BA_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_TITLE
     *
     * @return the value of blog_article.BA_TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_TITLE
     *
     * @param title the value for blog_article.BA_TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_SUMMARY
     *
     * @return the value of blog_article.BA_SUMMARY
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_SUMMARY
     *
     * @param summary the value for blog_article.BA_SUMMARY
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_LABEL_ID
     *
     * @return the value of blog_article.BA_LABEL_ID
     *
     * @mbggenerated
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_LABEL_ID
     *
     * @param labelId the value for blog_article.BA_LABEL_ID
     *
     * @mbggenerated
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_ARITICLE_TYPE
     *
     * @return the value of blog_article.BA_ARITICLE_TYPE
     *
     * @mbggenerated
     */
    public String getAriticleType() {
        return ariticleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_ARITICLE_TYPE
     *
     * @param ariticleType the value for blog_article.BA_ARITICLE_TYPE
     *
     * @mbggenerated
     */
    public void setAriticleType(String ariticleType) {
        this.ariticleType = ariticleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_CONTENT
     *
     * @return the value of blog_article.BA_CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_CONTENT
     *
     * @param content the value for blog_article.BA_CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_URL
     *
     * @return the value of blog_article.BA_URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_URL
     *
     * @param url the value for blog_article.BA_URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_CREATE_TIME
     *
     * @return the value of blog_article.BA_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_CREATE_TIME
     *
     * @param createTime the value for blog_article.BA_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_OPERATION_TIME
     *
     * @return the value of blog_article.BA_OPERATION_TIME
     *
     * @mbggenerated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_OPERATION_TIME
     *
     * @param operationTime the value for blog_article.BA_OPERATION_TIME
     *
     * @mbggenerated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_article.BA_READ_AMOUNT
     *
     * @return the value of blog_article.BA_READ_AMOUNT
     *
     * @mbggenerated
     */
    public Integer getReadAmount() {
        return readAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_article.BA_READ_AMOUNT
     *
     * @param readAmount the value for blog_article.BA_READ_AMOUNT
     *
     * @mbggenerated
     */
    public void setReadAmount(Integer readAmount) {
        this.readAmount = readAmount;
    }

    @Override
    public String toString() {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:SS:sss");
        String simdate = simpleDateFormat.format(createTime);
        return "Article{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", title='" + title + '\'' +
                ", summary='" + summary + '\'' +
                ", labelId='" + labelId + '\'' +
                ", ariticleType='" + ariticleType + '\'' +
                ", content='" + content + '\'' +
                ", url='" + url + '\'' +
                ", createTime=" + simdate +
                ", operationTime=" + operationTime +
                ", readAmount=" + readAmount +
                '}';
    }
}