package system.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_SEX
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_DIRTHDAY
     *
     * @mbggenerated
     */
    private Date dirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_MAIL
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_WECHAT
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_SKETCH
     *
     * @mbggenerated
     */
    private String sketch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_ENCRYPT_SALT
     *
     * @mbggenerated
     */
    private String encryptSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.BU_OPERATE_TIME
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.ID
     *
     * @return the value of blog_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.ID
     *
     * @param id the value for blog_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_USER_NAME
     *
     * @return the value of blog_user.BU_USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_USER_NAME
     *
     * @param userName the value for blog_user.BU_USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_PASSWORD
     *
     * @return the value of blog_user.BU_PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_PASSWORD
     *
     * @param password the value for blog_user.BU_PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_NAME
     *
     * @return the value of blog_user.BU_NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_NAME
     *
     * @param name the value for blog_user.BU_NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_SEX
     *
     * @return the value of blog_user.BU_SEX
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_SEX
     *
     * @param sex the value for blog_user.BU_SEX
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_ADDRESS
     *
     * @return the value of blog_user.BU_ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_ADDRESS
     *
     * @param address the value for blog_user.BU_ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_DIRTHDAY
     *
     * @return the value of blog_user.BU_DIRTHDAY
     *
     * @mbggenerated
     */
    public Date getDirthday() {
        return dirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_DIRTHDAY
     *
     * @param dirthday the value for blog_user.BU_DIRTHDAY
     *
     * @mbggenerated
     */
    public void setDirthday(Date dirthday) {
        this.dirthday = dirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_MOBILE
     *
     * @return the value of blog_user.BU_MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_MOBILE
     *
     * @param mobile the value for blog_user.BU_MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_MAIL
     *
     * @return the value of blog_user.BU_MAIL
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_MAIL
     *
     * @param mail the value for blog_user.BU_MAIL
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_WECHAT
     *
     * @return the value of blog_user.BU_WECHAT
     *
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_WECHAT
     *
     * @param wechat the value for blog_user.BU_WECHAT
     *
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_SKETCH
     *
     * @return the value of blog_user.BU_SKETCH
     *
     * @mbggenerated
     */
    public String getSketch() {
        return sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_SKETCH
     *
     * @param sketch the value for blog_user.BU_SKETCH
     *
     * @mbggenerated
     */
    public void setSketch(String sketch) {
        this.sketch = sketch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_ENCRYPT_SALT
     *
     * @return the value of blog_user.BU_ENCRYPT_SALT
     *
     * @mbggenerated
     */
    public String getEncryptSalt() {
        return encryptSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_ENCRYPT_SALT
     *
     * @param encryptSalt the value for blog_user.BU_ENCRYPT_SALT
     *
     * @mbggenerated
     */
    public void setEncryptSalt(String encryptSalt) {
        this.encryptSalt = encryptSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_CREATE_TIME
     *
     * @return the value of blog_user.BU_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_CREATE_TIME
     *
     * @param createTime the value for blog_user.BU_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.BU_OPERATE_TIME
     *
     * @return the value of blog_user.BU_OPERATE_TIME
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.BU_OPERATE_TIME
     *
     * @param operateTime the value for blog_user.BU_OPERATE_TIME
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", address='" + address + '\'' +
                ", dirthday=" + dirthday +
                ", mobile='" + mobile + '\'' +
                ", mail='" + mail + '\'' +
                ", wechat='" + wechat + '\'' +
                ", sketch='" + sketch + '\'' +
                ", encryptSalt='" + encryptSalt + '\'' +
                ", createTime=" + createTime +
                ", operateTime=" + operateTime +
                '}';
    }
}