package system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import system.model.Industry;
import system.model.IndustryExample;

public interface IndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int countByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int deleteByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int insert(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int insertSelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    List<Industry> selectByExample(IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    Industry selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Industry record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Industry record, @Param("example") IndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Industry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_industry
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Industry record);
}