package system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import system.model.Sundry;
import system.model.SundryExample;

public interface SundryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int countByExample(SundryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int deleteByExample(SundryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int insert(Sundry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int insertSelective(Sundry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    List<Sundry> selectByExample(SundryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    Sundry selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sundry record, @Param("example") SundryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sundry record, @Param("example") SundryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sundry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_sundry
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sundry record);
}